default:
  tags:
    - shell-runner-38

stages:
  - build_temp_image
  - smoke_test
  - push_release
  - push_ali

variables:
  PROJECT_NAME: primer_demux
  TEMP_TAG: tmp-$CI_COMMIT_SHORT_SHA

  PRIMER_SMOKE_TEST_DIR: /data/CI_CD_DATASETS/PROJECT_PRIMER/smoke_test

  RELEASE_TAG: $CI_COMMIT_TAG
  CI_REGISTRY_IMAGE: 192.168.3.38:5000/algo/primer_demux
  ALI_ACR_REGISTRY_IMAGE: geneus-registry.cn-hongkong.cr.aliyuncs.com/algo/primer_demux

  GIT_SUBMODULE_STRATEGY: recursive

  # 上一次正式发布版本，用作 no-diff 对照
  STABLE_TAG: stable


build_temp_image:
  stage: build_temp_image
  script:
    - whoami
    - echo "📦 Building temp image..."
    - DOCKER_BUILDKIT=0 docker build -t $PROJECT_NAME:$TEMP_TAG .
  rules:
    # 分支提交时构建
    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE != "web"'
      when: on_success

    # tag 发布时也必须构建
    - if: '$CI_COMMIT_TAG'
      when: on_success


smoke_test:
  stage: smoke_test
  script:
    - echo "🧪 Running smoke test..."
    - whoami
    - id

    - echo "Smoke test dir = $PRIMER_SMOKE_TEST_DIR"
    - test -n "$PRIMER_SMOKE_TEST_DIR"
    - test -d "$PRIMER_SMOKE_TEST_DIR"
    - ls -lh "$PRIMER_SMOKE_TEST_DIR"

    - mkdir -p "$PRIMER_SMOKE_TEST_DIR/ci_test_output"
    - rm -rf "$PRIMER_SMOKE_TEST_DIR/ci_test_output"/*
    - chmod -R 777 "$PRIMER_SMOKE_TEST_DIR/ci_test_output"

    - >
      python3 python_scripts/run_primer_test.py
      --test-file-dir "$PRIMER_SMOKE_TEST_DIR"
      --output-root "$PRIMER_SMOKE_TEST_DIR/ci_test_output"
      --docker-image "$PROJECT_NAME:$TEMP_TAG"

    - echo "Smoke test output:"
    - find "$PRIMER_SMOKE_TEST_DIR/ci_test_output" -maxdepth 4 -type f -exec ls -lh {} \;

  except:
    - tags
    - web

push_release:
  stage: push_release
  needs:
    - smoke_test
  script:
    - echo "📤 Pushing release image..."
    - docker tag $PROJECT_NAME:$TEMP_TAG $CI_REGISTRY_IMAGE:$RELEASE_TAG
    - docker push $CI_REGISTRY_IMAGE:$RELEASE_TAG
    - echo "📤 Pushing release image DONE. $CI_REGISTRY_IMAGE:$RELEASE_TAG"
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success


push_ali:
  stage: push_ali
  needs:
    - push_release
  script:
    - whoami
    - echo "Pushing release image to Aliyun ACR"
    - echo "Source image = ${CI_REGISTRY_IMAGE}:${RELEASE_TAG}"
    - echo "Target image = ${ALI_ACR_REGISTRY_IMAGE}:${RELEASE_TAG}"
    - docker pull ${CI_REGISTRY_IMAGE}:${RELEASE_TAG}
    - docker tag ${CI_REGISTRY_IMAGE}:${RELEASE_TAG} ${ALI_ACR_REGISTRY_IMAGE}:${RELEASE_TAG}
    - docker push ${ALI_ACR_REGISTRY_IMAGE}:${RELEASE_TAG}
    - echo "Push to Aliyun ACR done"
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success