{% set name = "primer_demux" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - pkg-config
    - make
  host:
    - htslib
    - openssl
    - zlib
    - bzip2
    - xz
  run:
    - htslib
    - openssl
    - zlib
    - bzip2
    - xz

test:
  commands:
    - primer_demux --version
    - primer_demux --help

about:
  home: https://github.com/huiN95/primer_demux
  license: MIT
  license_family: MIT
  summary: "A high-performance tool for demultiplexing sequencing reads based on primer sequences."
  dev_url: https://github.com/huiN95/primer_demux

extra:
  recipe-maintainers:
    - huiN95
